//this file is auto-generated by tools/index.ts
use tauri::{Builder, Wry};

mod steam;

pub fn invoke_handler(builder: Builder<Wry>) -> Builder<Wry> { 
  builder.invoke_handler(tauri::generate_handler![
    steam::steamRestart,
    steam::account::steamAccountDelete,
    steam::account::steamAccountCurrent,
    steam::steamPath,
    steam::steamUsers
  ])
}